authentication/urls.py
from django.urls import path
from authentication.views import register,login, user_logout

app_name = 'auth'

urlpatterns = [
    path('register', register, name='register'),
    path('login', login, name='auth_login'),
    path('logout', user_logout, name='logout'),
]

chat/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.messages_page),
    path('<int:thread_id>/', views.messages_page, name='messages_page'),

]

parentie/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('chat/', include('chat.urls')),

    path('', include('forum_v2.urls')),
    path('donor/', include('donor.urls')),
    path('user_profile/', include('user_profile.urls')),

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authentication/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class RegisteredUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    peran = models.CharField()
    nama = models.CharField()
    umur = models.IntegerField(default=None, null=True, blank=True)
    domisili = models.CharField()
    agama = models.CharField(default=None, null=True, blank=True)
    golongan_darah = models.CharField(default=None, null=True, blank=True)
    kondisi_ibu = models.CharField(default=None, null=True, blank=True)
    umur_bayi = models.IntegerField(default=None, null=True, blank=True)
    jenis_kelamin_bayi = models.CharField(default=None, null=True, blank=True)

authentication/views.py
from django.shortcuts import render

# Create your views here.
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from authentication.models import RegisteredUser
import json
from django.shortcuts import render
from django.conf import settings
import os

@csrf_exempt
def register(request):
    if (request.method == "POST"):
        try:
            username = request.POST["username"]
            password = request.POST["password"]
            nama = request.POST["nama"]
            peran = request.POST["peran"]
            domisili = request.POST["domisili"]
            agama = request.POST["agama"]
            umur = request.POST["umur"]
            if umur == '':
                umur = None
            
            try: 
                golongan_darah = request.POST["golongan_darah"]
            except:
                golongan_darah = None

            try: 
                kondisi_ibu = request.POST["kondisi_ibu"]
            except:
                kondisi_ibu = None

            try: 
                umur_bayi = request.POST["umur_bayi"]
            except:
                umur_bayi = None

            try:
                jenis_kelamin = request.POST["jenis_kelamin"]
            except:
                jenis_kelamin = None

            user = User.objects.create_user(username=username, password=password)
            pengguna_baru = RegisteredUser.objects.create(user=user, nama = nama, peran = peran, domisili = domisili, agama = agama, umur = umur, golongan_darah = golongan_darah, kondisi_ibu = kondisi_ibu, umur_bayi = umur_bayi, jenis_kelamin_bayi = jenis_kelamin)
            
            pengguna_baru.save()
            return redirect('auth:auth_login')
        
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)
    

    json_file_path = os.path.join(settings.BASE_DIR, 'static/json/kota.json')

    with open(json_file_path, 'r', encoding='utf-8') as json_file:
        data = json.load(json_file)
        cities = [item['text'] for item in data['result']]
        context = {
            'cities': cities
        }
    return render(request, "register.html", context)


from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login, logout
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.contrib.auth.models import User


@csrf_exempt
def login(request):
    if (request.method == "POST"):
        try:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    auth_login(request, user)
                    # Redirect to a success page.
                    request.session['username'] = username
                    request.session['user_id'] = user.id
                    
                    return redirect('home')

                else:
                    return JsonResponse({
                    "status": False,
                    "message": "Failed to Login, Account Disabled."
                    }, status=401)

            else:
                return JsonResponse({
                "status": False,
                "message": "Failed to Login, check your email/password."
                }, status=401)
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)
     
    return render(request, 'login.html')

    

from django.contrib.auth.decorators import login_required

@login_required
def get_session(request):
    # Access the session data
    username = request.session.get('username')
    user_id = request.session.get('user_id')

    if username and user_id:
        return username
    else:
        return "no session data found!"



@csrf_exempt
def user_logout(request):
    if request.method == "POST":
        try:
            logout(request)
            request.session.flush()
            return JsonResponse({
                "status": True,
                "message": "Successfully Logged Out!",
            }, status=200)
        except Exception as e:
            return JsonResponse({"error": str(e)}, status=400)

    return JsonResponse({
        "status": False,
        "message": "Invalid request method."
    }, status=405)

authentication/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
    <title>Login</title>
{% endblock meta %}
{% block content %}
    <div class="flex items-center justify-center min-h-screen" style="background-color: #F4FEFF;">
        <div class="container mx-auto max-w-md shadow-md rounded-lg overflow-hidden bg-white">
            <div class="py-8 px-6 sm:px-10">
                <div class="mb-8 text-center">
                    <h2 class="text-2xl font-bold leading-9 tracking-tight text-gray-900">Login</h2>
                </div>
                <form class="space-y-6" action="{% url 'auth:auth_login' %}" method="POST">
                    {% csrf_token %}
                    <div>
                        <div class="flex items-center justify-between">
                            <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
                        </div>
                        <div class="mt-2">
                            <input id="username" name="username" type="text" autocomplete="username" required class="block w-full rounded-md border-0 py-1.5 px-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </div>
                    </div>
                    <div>
                        <div class="flex items-center justify-between">
                            <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
                        </div>
                        <div class="mt-2">
                            <input id="password" name="password" type="password" autocomplete="current-password" required class="block w-full rounded-md border-0 py-1.5 px-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">
                        </div>
                    </div>
                    <div class="flex justify-center">
                        <button type="submit" class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-6 border border-blue-500 hover:border-transparent rounded-full">
                            Login
                        </button>
                    </div>
                </form>
                <p class="mt-10 text-center text-sm text-gray-500">
                    Belum punya akun?
                    <a href="{% url 'auth:register' %}" class="font-semibold leading-6 text-indigo-600 hover:text-indigo-500">Daftar di sini</a>
                </p>
            </div>
        </div>
    </div>
{% endblock content %}